package: package.h package.cpp
	g++ package.cpp -c --std=c++20

puzzle1: puzzle1.cpp package.o
	g++ puzzle1.cpp package.o -o puzzle1 --std=c++20

puzzle2: puzzle2.cpp package.o
	g++ puzzle2.cpp package.o -o puzzle2 --std=c++20
